### ISSUE TITLE
Verbesserung der Doku

### ISSUE THREAD

**Issue by notesjor** [KorAP/KorAP-Docker#6]
- Der Befehl zum Starten des Containers funktioniert so nicht auf Windows. Anstelle von:
INDEX=./index docker-compose --profile=lite up
ist folgender Befehl nötig (PoweShell):
$env:INDEX="./index"; docker-compose --profile=lite up
- Außerdem fehlt aktuell der Parameter PWD im Beispiel:
INDEX=./index PWD=./example docker-compose --profile=lite up
bzw. Windows PowerShell
$env:INDEX="./index"; $env:PWD="./example"; docker-compose --profile=init up

**Comment by Akron** [comment]
Tatsächlich vernachlässigen wir ständig Windows in unseren Dokumentationen ... Vermutlich gibt es für PWD auch eine bessere, portable Lösung anstatt es per env zu setzen. Was den Index-Parameter betrifft - den sollten wir auf jeden Fall für Windows auch angeben.

**Comment by kupietz** [comment]
> Tatsächlich vernachlässigen wir ständig Windows in unseren Dokumentationen ... Vermutlich gibt es für PWD auch eine bessere, portable Lösung anstatt es per env zu setzen. 

`$(pwd)` ?

**Comment by kupietz** [comment]
>     * Außerdem fehlt aktuell der Parameter PWD im Beispiel:
>       INDEX=./index PWD=./example docker-compose --profile=lite up
>       bzw. Windows PowerShell
>       $env:INDEX="./index"; $env:PWD="./example"; docker-compose --profile=init up

In der PowerShell ist PWD jetzt bei mir korrekt gesetzt. Mit cygwin scheint, außer mit `--profile=full`, alles wie angegeben zu funktionieren.
